"""init

Revision ID: 7827d34bdc1b
Revises:
Create Date: 2026-02-21 11:56:50.614149

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7827d34bdc1b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("idx_project_name", "projects", ["name"], unique=False)
    op.create_table(
        "snapshots",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("revision_id", sa.String(), nullable=False),
        sa.Column("prev_revision_id", sa.String(), nullable=True),
        sa.Column(
            "schema_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("diff_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("snapshots")
    op.drop_index("idx_project_name", table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
